schema_version: 1

context:
  version: "1.6.0"

package:
  name: ejson
  version: ${{ version }}

source:
  url: https://github.com/Shopify/ejson/archive//v${{ version }}.tar.gz
  sha256: 6ca032ec72065b5e2a54102459b0024118aa695ed51fec13321ef510be2c77d8

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - ejson --help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: EJSON is a small library to manage encrypted secrets using asymmetric encryption.
  homepage: https://github.com/Shopify/ejson
  repository: https://github.com/Shopify/ejson

extra:
  recipe-maintainers:
    - danielnachun
